news:
    resource: "@NewsBundle/Resources/config/routing.yml"
    prefix:   /

_welcome:
    pattern: /
    defaults: {_controller: AppBundle:Default:index}

userbundle:
  resource: "@UserBundle/Resources/config/routing.yml"

appbundle:
     resource:  "@AppBundle/Resources/config/routing.yml"

