_welcome:
    pattern: /
    defaults: {_controller: AppBundle:Default:index}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

appbundle:
     resource:  "@AppBundle/Resources/config/routing.yml"