baseforms:
    path:     /
    defaults: { _controller: "AppBundle:BaseForms:index" }

baseforms_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:BaseForms:show" }

baseforms_new:
    path:     /new
    defaults: { _controller: "AppBundle:BaseForms:new" }

baseforms_create:
    path:     /create
    defaults: { _controller: "AppBundle:BaseForms:create" }
    methods:  POST

baseforms_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:BaseForms:edit" }

baseforms_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:BaseForms:update" }
    methods:  [POST, PUT]

baseforms_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:BaseForms:delete" }
    methods:  [POST, DELETE]
