formreport:
    path:     /{_locale}/
    defaults: { _controller: "AppBundle:FormReport:index", _locale:ru  }
    requirements:
        _locale: ru|en

formreport_show:
    path:     /{_locale}/{id}/show
    defaults: { _controller: "AppBundle:FormReport:show", _locale:ru  }
    requirements:
        _locale: ru|en

formreport_new:
    path:     /{_locale}/new
    defaults: { _controller: "AppBundle:FormReport:new", _locale:ru  }
    requirements:
        _locale: ru|en

formreport_create:
    path:     /{_locale}/create
    defaults: { _controller: "AppBundle:FormReport:create", _locale:ru  }
    requirements:
        _locale: ru|en
    methods:  POST

formreport_edit:
    path:     /{_locale}/{id}/edit
    defaults: { _controller: "AppBundle:FormReport:edit", _locale:ru  }
    requirements:
        _locale: ru|en

formreport_update:
    path:     /{_locale}/{id}/update
    defaults: { _controller: "AppBundle:FormReport:update", _locale:ru  }
    requirements:
        _locale: ru|en
    methods:  [POST, PUT]

formreport_delete:
    path:     /{_locale}/{id}/delete
    defaults: { _controller: "AppBundle:FormReport:delete", _locale:ru  }
    requirements:
        _locale: ru|en
    methods:  [POST, DELETE]
