report:
    path:     /
    defaults: { _controller: "AppBundle:Report:index" }

report_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Report:show" }

report_new:
    path:     /new
    defaults: { _controller: "AppBundle:Report:new" }

report_create:
    path:     /create
    defaults: { _controller: "AppBundle:Report:create" }
    methods:  POST

report_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Report:edit" }

report_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Report:update" }
    methods:  [POST, PUT]

report_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Report:delete" }
    methods:  [POST, DELETE]
