UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }

