UserBundle\Entity\User:
    type:  entity
    table: fos_user
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        curatorUserId:
            type: integer
            nullable: true
            unsigned: true
            column: curator_user_id
        description:
            type: text
            nullable: true
            length: 65535
            fixed: false
        phone:
            type: string
            nullable: true
            length: 255
            fixed: false
        inn:
            type: string
            nullable: true
            length: 25
            fixed: false
        numberSocialnFond:
            type: string
            nullable: true
            length: 255
            fixed: false
        bank:
            type: string
            nullable: true
            length: 255
            fixed: false
        bankAccount:
            type: string
            nullable: true
            length: 255
            fixed: false
        bankBik:
            type: string
            nullable: true
            length: 255
            fixed: false
        director:
            type: string
            nullable: true
            length: 255
            fixed: false
        directorPost:
            type: string
            nullable: true
            length: 255
            fixed: false
        dateRegistration:
            type: date
            nullable: true
            length: 255
            fixed: false
        okved:
            type: string
            nullable: true
            length: 255
            fixed: false
        directorPhone:
            type: string
            nullable: true
            length: 255
            fixed: false
        buhgalter:
            type: string
            nullable: true
            length: 255
            fixed: false
        buhgalterphone:
            type: string
            nullable: true
            length: 255
            fixed: false
        phisicalAdress:
            type: string
            nullable: true
            length: 255
            fixed: false
        urAdress:
            type: string
            nullable: true
            length: 255
            fixed: false
        mailAdress:
            type: string
            nullable: true
            length: 255
            fixed: false
        site:
            type: string
            nullable: true
            length: 255
            fixed: false
        fullNameOrganization:
            type: string
            nullable: true
            length: 255
            fixed: false
        shortNameOrganization:
            type: string
            nullable: true
            length: 255
            fixed: false
        timeJob:
            type: string
            nullable: true
            length: 255
            fixed: false
        gns:
            type: string
            nullable: true
            length: 255
            fixed: false
        okpo:
            type: string
            nullable: true
            length: 255
            fixed: false
    manyToOne:
        curatorUser:
            targetEntity: User
            inversedBy: fosUser
            joinColumn:
                name: curator_user_id
                referencedColumnName: id
    manyToMany:
        groups:
            targetEntity: Group
            joinTable:
                name: fos_user_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    group_id:
                        referencedColumnName: id
    lifecycleCallbacks: {  }

