user_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /user

user_group:
    resource: "@UserBundle/Resources/config/routing/group.yml"
    prefix:   /group

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

userbundle_user:
    resource: "@UserBundle/Resources/config/routing/user.yml"
    prefix:   /user

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group