AppBundle\Entity\Area:
    type: entity
    table: area
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nameArea:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: name_area
    oneToMany:
        baseForms:
            targetEntity: BaseForms
            mappedBy: area
    lifecycleCallbacks: {  }
