AppBundle\Entity\BaseForms:
    type: entity
    table: base_forms
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        formReport:
            type: integer
            column: form_report
        typeReport:
            type: integer
            nullable: false
            column: type_report
        description:
            type: text
            nullable: true
            column: description
        organization:
            type: integer
            nullable: false
            unsigned: false
            column: organization
        fileAdress:
            type: string
            length: 255
            column: file_adress
        dateAccepted:
            type: datetime
            nullable: false
            column: date_accepted
    lifecycleCallbacks: {  }
