AppBundle\Entity\BaseForms:
    type: entity
    table: base_forms
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        formReport:
            type: integer
            nullable: false
            unsigned: false
            column: form_report
        typeReportId:
            type: integer
            nullable: false
            unsigned: false
            column: type_report_id
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        organization:
            type: integer
            nullable: false
            unsigned: false
        fileAdress:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: file_adress
        dateAccepted:
            type: datetime
            nullable: false
            column: date_accepted
        imageName:
            type: string
            length: 255
            fixed: false
            column: image_name

    manyToOne:
        typeReport:
            targetEntity: TypeReport
            inversedBy: baseForms
            joinColumn:
                name: type_report_id
                referencedColumnName: id

    lifecycleCallbacks: {  }

