AppBundle\Entity\BaseForms:
    type: entity
    table: base_forms
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeReportId:
            type: integer
            nullable: false
            unsigned: false
            column: type_report_id
        formReportId:
            type: integer
            nullable: false
            unsigned: false
            column: form_report_id
        areaId:
            type: integer
            nullable: false
            unsigned: false
            column: area_id
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        organizationId:
            type: integer
            nullable: false
            unsigned: false
            column: organization_id
        createUserId:
            type: integer
            nullable: false
            unsigned: false
            column: create_user_id
        dateAccepted:
            type: datetime
            nullable: false
            column: date_accepted
        imageName:
            type: string
            length: 255
            fixed: false
            column: image_name
        isreport:
            type: integer
            nullable: true
            unsigned: false
            column: is_report
    manyToOne:
        typeReport:
            targetEntity: TypeReport
            inversedBy: baseForms
            joinColumn:
                name: type_report_id
                referencedColumnName: id
        formReport:
            targetEntity: FormReport
            inversedBy: baseForms
            joinColumn:
                name: form_report_id
                referencedColumnName: id
        organization:
            targetEntity: Organization
            inversedBy: baseForms
            joinColumn:
                name: organization_id
                referencedColumnName: id
        createUser:
            targetEntity: UserBundle\Entity\User
            inversedBy: baseForms
            joinColumn:
                name: create_user_id
                referencedColumnName: id
        area:
            targetEntity: Area
            inversedBy: baseForms
            joinColumn:
                name: area_id
                referencedColumnName: id
    lifecycleCallbacks: {  }

