AppBundle\Entity\Organization:
    type: entity
    table: organization
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        organizationName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: organization_name
        organizationPhone:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: organization_phone
        organizationDescription:
            type: text
            nullable: true
            length: null
            fixed: false
            column: organization_description
        organizationShortName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: organization_short_name
    oneToMany:
        baseForms:
            targetEntity: BaseForms
            mappedBy: organization
    lifecycleCallbacks: {  }
