AppBundle\Entity\Report:
    type: entity
    table: report
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        formReport:
            type: integer
            column: form_report
        typeReport:
            type: integer
            nullable: false
            column: type_report
        dateIn:
            type: datetime
            nullable: false
            column: date_in
        description:
            type: text
            nullable: true
            column: description
        organization:
            type: integer
            nullable: false
            unsigned: false
            column: organization
        status:
            type: integer
            nullable: false
            unsigned: false
            column: status
        fileAdress:
            type: string
            length: 255
            column: file_adress
        area:
            type: integer
            nullable: false
            unsigned: false
            column: area
        dateAccepted:
            type: datetime
            nullable: false
            column: date_accepted
    lifecycleCallbacks: {  }
