AppBundle\Entity\Report:
    type: entity
    table: report
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateIn:
            type: datetime
            nullable: false
            column: date_in
        description:
            type: text
            nullable: true
            length: null
            fixed: false
        organization:
            type: integer
            nullable: false
            unsigned: false
        status:
            type: integer
            nullable: false
            unsigned: false
        dateAccepted:
            type: datetime
            nullable: false
            column: date_accepted
        typeReport:
            type: integer
            nullable: false
            unsigned: false
            column: type_report
        fileAdress:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: file_adress
        area:
            type: integer
            nullable: false
            unsigned: false
        formReport:
            type: integer
            nullable: false
            unsigned: false
            column: form_report
    lifecycleCallbacks: {  }
