AppBundle\Entity\Status:
    type: entity
    table: status
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        statusName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: status_name
    lifecycleCallbacks: {  }
