AppBundle\Entity\TypeReport:
    type: entity
    table: type_report
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        typeName:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: type_name
    oneToMany:
        baseForms:
            targetEntity: BaseForms
            mappedBy: typeReport

    lifecycleCallbacks: {  }
